name: following_feature_agent
features:
  - name: comparator
    operator: ge
    dependencies:
      - running_average_20_for_stock_data
      - running_average_60_for_stock_data
  - name: running_average_analysis
    visible: False
    num_days: 20
    dependencies:
      - stock_data
  - name: running_average_analysis
    visible: False
    num_days: 60
    dependencies:
      - stock_data
